[package]
name = "matmul-benchmark"
version = "0.1.0"
edition = "2024"
build = "build.rs"
links = "mlx"

[[bin]]
name = "matmul-benchmark"
path = "src/main.rs"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.187"
uzu = { path = "../uzu" }
metal = "0.32.0"
mpsgraph = "0.2.0"
half = "2.4"
objc2 = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
walkdir = "2.5.0"
cmake = "0.1.57"
autocxx-build = "0.30.0"
