[package]
name = "matmul-benchmark"
version.workspace = true
edition.workspace = true
build = "build.rs"
links = "mlx"

[[bin]]
name = "matmul-benchmark"
path = "src/main.rs"

[dependencies]
autocxx.workspace = true
cxx.workspace = true
uzu = { workspace = true }
metal.workspace = true
mpsgraph.workspace = true
half.workspace = true
objc2.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
walkdir.workspace = true
cmake.workspace = true
autocxx-build.workspace = true
