[workspace]
members = ["crates/cli", "crates/uzu"]
resolver = "3"

[workspace.package]
version = "0.1.4"
edition = "2024"
license = "MIT"
authors = ["Mirai Tech <https://trymirai.com>"]
repository = "https://github.com/trymirai/uzu"

[profile.release]
lto = true

[profile.test]
inherits = "release"
