[workspace]
members = ["crates/cli", "crates/uzu", "crates/benchmarks"]
resolver = "3"

[workspace.package]
version = "0.1.7"
edition = "2024"
rust-version = "1.92"
license = "MIT"
authors = ["Mirai Tech <https://trymirai.com>"]
repository = "https://github.com/trymirai/uzu"

[workspace.dependencies]
benchmarks = { path = "crates/benchmarks" }
uzu = { path = "crates/uzu" }
xgrammar = { package = "xgrammar-rs", version = "0.1", features = ["hf"] }
half = { version = "2.7", features = ["bytemuck", "num-traits"] }
ndarray = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokenizers = "0.22"
mpsgraph = "0.2"
objc2 = "0.6"
objc2-foundation = "0.3"
metal = { package = "mtl-rs", version = "0.1" }
block2 = "0.6"
bytemuck = "1.23"
num-traits = "0.2"
regex = "1.12"
libc = "0.2"
bitflags = "2.10"
minijinja = "2.15"
minijinja-contrib = { version = "2.15", features = ["pycompat"] }
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"
sysinfo = "0.38"
itertools = "0.14"
schemars = { version = "1.2", features = ["derive"] }
is_close = "0.1"
serde_json5 = "0.2"
anyhow = "1.0"
async-trait = "0.1"
bindgen = "0.72"
walkdir = "2.5"
depfile = "0.1"
tempfile = "3.24"
clang-ast = "0.1"
futures = "0.3"
tokio = { version = "1.49", features = ["full"] }
blake3 = "1.8"
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
prettyplease = "0.2"
mach2 = "0.6"
ctrlc = "3.5"
indicatif = "0.18"
inquire = "0.9"
console = "0.16"
rocket = { version = "0.5", features = ["json"] }
uuid = { version = "1.20", features = ["v4"] }
comfy-table = "7.2"
autocxx = "0.30"
cxx = "1.0"
cmake = "0.1"
autocxx-build = "0.30"

# optimize the build script in debug builds
[profile.dev.build-override]
opt-level = 3

[profile.release]
lto = "thin"
