[package]
name = "benchmarks"
version.workspace = true
edition = "2024"

[dependencies]
uzu = { path = "../uzu" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.148"
sysinfo = "0.37.2"
libc = "0.2.178"
mach2 = "0.6.0"
half = { version = "2.6.0", features = ["bytemuck", "num-traits"] }
objc2 = "0.6.2"
metal = "0.32.0"
