[package]
name = "cli"
version = "0.1.6"
edition = "2024"

[[bin]]
name = "uzu_cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
uzu = { path = "../uzu" }
ctrlc = "3.4.1"
indicatif = "0.18.0"
inquire = "0.7.5"
console = "0.16.0"
rocket = { version = "0.5.1", features = ["json"] }
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }
