[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[features]
default = []
audio-prototype-cli = ["uzu/audio-prototype-cli"]

[dependencies]
clap.workspace = true
uzu.workspace = true
benchmarks.workspace = true
ctrlc.workspace = true
indicatif.workspace = true
inquire.workspace = true
console.workspace = true
rocket.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
comfy-table.workspace = true
