[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uzu.workspace = true
benchmarks.workspace = true
ctrlc.workspace = true
indicatif.workspace = true
inquire.workspace = true
console.workspace = true
rocket.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
comfy-table.workspace = true
hound = "3.5.1"
rubato = "1.0.0"
audioadapter-buffers = "2.0.0"
metal.workspace = true
