[package]
name = "uzu"
version = "0.1.6"
edition = "2024"
build = "build.rs"

[dependencies]
half = { version = "2.6.0", features = ["bytemuck", "num-traits"] }
ndarray = "0.16.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
tokenizers = "0.22.0"
mpsgraph = "0.2.0"
objc2 = "0.6.2"
objc2-foundation = "0.3.1"
metal = "0.32.0"
bytemuck = "1.23.2"
num-traits = "0.2.19"
regex = "1.11.2"
libc = "0.2.175"
bitflags = "2.9.4"
minijinja = "2.12.0"
minijinja-contrib = { version = "2.12.0", features = ["pycompat"] }
clap = { version = "4.5.47", features = ["derive"] }
rand = "0.9.2"
sysinfo = "0.37.0"

[dev-dependencies]
is_close = "0.1.3"
serde_json5 = "0.2.1"

[features]
default = ["metal-shaders"]
metal-shaders = []

[[test]]
name = "moe"
path = "tests/moe/mod.rs"
