[package]
name = "uzu"
version = "0.1.5"
edition = "2024"
build = "build.rs"

[dependencies]
half = { version = "2.7.1", features = ["bytemuck", "num-traits"] }
ndarray = "0.17.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokenizers = "0.22.1"
mpsgraph = "0.2.0"
objc2 = "0.6.3"
objc2-foundation = "0.3.2"
metal = "0.32.0"
bytemuck = "1.24.0"
num-traits = "0.2.19"
regex = "1.12.2"
libc = "0.2.177"
bitflags = "2.10.0"
minijinja = "2.12.0"
minijinja-contrib = { version = "2.12.0", features = ["pycompat"] }
clap = { version = "4.5.50", features = ["derive"] }
rand = "0.9.2"
sysinfo = "0.37.2"
xgrammar = { package = "xgrammar-rs", version = "0.1.26", features = ["hf"] }

[dev-dependencies]
is_close = "0.1.3"
serde_json5 = "0.2.1"
schemars = { version = "1.0.5", features = ["derive"] }

[features]
default = ["metal-shaders"]
metal-shaders = []

[[test]]
name = "moe"
path = "tests/moe/mod.rs"
