[package]
name = "uzu"
version.workspace = true
edition.workspace = true
build = "build/main.rs"

[dependencies]
xgrammar.workspace = true
half.workspace = true
ndarray.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokenizers.workspace = true
mpsgraph.workspace = true
objc2.workspace = true
objc2-foundation.workspace = true
metal.workspace = true
block.workspace = true
bytemuck.workspace = true
num-traits.workspace = true
regex.workspace = true
libc.workspace = true
bitflags.workspace = true
minijinja.workspace = true
minijinja-contrib.workspace = true
clap.workspace = true
rand.workspace = true
sysinfo.workspace = true
itertools.workspace = true
schemars.workspace = true

[dev-dependencies]
is_close.workspace = true
serde_json5.workspace = true
schemars.workspace = true
mpsgraph.workspace = true

[build-dependencies]
anyhow.workspace = true
async-trait.workspace = true
bindgen.workspace = true
walkdir.workspace = true
depfile.workspace = true
tempfile.workspace = true
serde.workspace = true
serde_json.workspace = true
clang-ast.workspace = true
futures.workspace = true
tokio.workspace = true
blake3.workspace = true
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true
prettyplease.workspace = true
itertools.workspace = true

[features]
default = ["metal"]

metal = []
metal-nax = []

tracing = []

[[test]]
name = "moe"
path = "tests/moe/mod.rs"
