[package]
name = "uzu"
version.workspace = true
edition = "2024"
build = "build/main.rs"

[dependencies]
# "linked" link the Vulkan loader at compile time
# without "linked" device.device_fn_1_0.allocate_command_buffers have error
# "read memory from 0x1026f98b4 failed (0 of 8 bytes read)" on macOS
ash = { version = "0.38.0", features = ["linked"], optional = true }
xgrammar = { package = "xgrammar-rs", version = "0.1.29", features = ["hf"] }
half = { version = "2.6.0", features = ["bytemuck", "num-traits"] }
ndarray = "0.17.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.16"
tokenizers = "0.22.2"
mpsgraph = "0.2.0"
objc2 = "0.6.2"
objc2-foundation = "0.3.1"
metal = "0.32.0"
block = "0.1.6"
bytemuck = "1.23.2"
num-traits = "0.2.19"
regex = "1.11.2"
libc = "0.2.175"
bitflags = "2.9.4"
minijinja = "2.12.0"
minijinja-contrib = { version = "2.12.0", features = ["pycompat"] }
rand = "0.9.2"
sysinfo = "0.37.2"
itertools = "0.14.0"
schemars = "1.0.5"

[dev-dependencies]
is_close = "0.1.3"
serde_json5 = "0.2.1"
schemars = { version = "1.0.5", features = ["derive"] }
mpsgraph = "0.2.0"

[build-dependencies]
bindgen = "0.72.1"
futures = "0.3"
regex = "1.12.2"
shaderc = "0.10.1"
tokio = { version = "1.49.0", features = ["full"] }
walkdir = "2.5.0"

[features]
default = ["metal-shaders"]
metal-shaders = []
tracing = []
vulkan = ["dep:ash"]

[[test]]
name = "moe"
path = "tests/moe/mod.rs"
